// flow-typed signature: 9bc564d3cd08f6544097cce43ceee17b
// flow-typed version: <<STUB>>/storybook-readme_v^5.0.3/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-readme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-readme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-readme/backwardCompatibility/env/common/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/backwardCompatibility/env/react/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/backwardCompatibility/env/vue/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/backwardCompatibility/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/backwardCompatibility/with-docs' {
  declare module.exports: any;
}

declare module 'storybook-readme/backwardCompatibility/with-readme' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/Marked/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/Preview/DocPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/Preview/FooterPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/Preview/HeaderPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/Preview/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/Preview/StoryPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/ReadmeContent/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/components/ReadmeSidebar/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/const' {
  declare module.exports: any;
}

declare module 'storybook-readme/register' {
  declare module.exports: any;
}

declare module 'storybook-readme/registerWithPanelTitle' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/config' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/getDocsLayout' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/getParameters' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/getPropsTables/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/getPropsTables/parseProps' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/highlite' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/marked' {
  declare module.exports: any;
}

declare module 'storybook-readme/services/transformEmojis' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemeCss' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/a11y-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/a11y-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/agate.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/an-old-hope.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/androidstudio.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/arduino-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/arta.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/ascetic.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-cave-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-cave-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-dune-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-dune-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-estuary-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-estuary-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-forest-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-forest-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-heath-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-heath-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-lakeside-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-lakeside-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-plateau-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-plateau-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-savanna-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-savanna-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-seaside-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-seaside-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-sulphurpool-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atelier-sulphurpool-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atom-one-dark-reasonable.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atom-one-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/atom-one-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/codepen-embed.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/color-brewer.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/darcula.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/darkula.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/default.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/docco.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/dracula.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/far.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/foundation.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/github-gist.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/github.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/gml.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/googlecode.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/grayscale.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/gruvbox-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/gruvbox-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/hopscotch.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/hybrid.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/idea.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/ir-black.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/isbl-editor-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/isbl-editor-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/kimbie.dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/kimbie.light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/lightfair.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/magula.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/mono-blue.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/monokai-sublime.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/monokai.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/nord.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/obsidian.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/ocean.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/paraiso-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/paraiso-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/purebasic.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/qtcreator_dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/qtcreator_light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/railscasts.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/rainbow.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/routeros.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/shades-of-purple.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/solarized-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/solarized-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/sunburst.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/tomorrow-night-blue.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/tomorrow-night-bright.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/tomorrow-night-eighties.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/tomorrow-night.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/tomorrow.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/vs.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/vs2015.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/xcode.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/xt256.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/codeThemes/zenburn.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/githubMarkdownCss' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/a11y-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/atom-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/base16-ateliersulphurpool.light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/cb.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/darcula.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/duotone-dark.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/duotone-earth.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/duotone-forest.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/duotone-light.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/duotone-sea.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/duotone-space.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/ghcolors.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/github.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/hopscotch.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/pojoaque.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/vs.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/prismCodeThemes/xonokai.css' {
  declare module.exports: any;
}

declare module 'storybook-readme/styles/styleFactory' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/components/Preview/DocPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/components/Preview/FooterPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/components/Preview/HeaderPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/components/Preview/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/components/Preview/StoryPreview' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/components/ReadmeContent/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/docs-loader' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/index' {
  declare module.exports: any;
}

declare module 'storybook-readme/vue/updateWebpackConfig' {
  declare module.exports: any;
}

declare module 'storybook-readme/with-docs' {
  declare module.exports: any;
}

declare module 'storybook-readme/with-readme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-readme/backwardCompatibility/env/common/index.js' {
  declare module.exports: $Exports<'storybook-readme/backwardCompatibility/env/common/index'>;
}
declare module 'storybook-readme/backwardCompatibility/env/react/index.js' {
  declare module.exports: $Exports<'storybook-readme/backwardCompatibility/env/react/index'>;
}
declare module 'storybook-readme/backwardCompatibility/env/vue/index.js' {
  declare module.exports: $Exports<'storybook-readme/backwardCompatibility/env/vue/index'>;
}
declare module 'storybook-readme/backwardCompatibility/index.js' {
  declare module.exports: $Exports<'storybook-readme/backwardCompatibility/index'>;
}
declare module 'storybook-readme/backwardCompatibility/with-docs.js' {
  declare module.exports: $Exports<'storybook-readme/backwardCompatibility/with-docs'>;
}
declare module 'storybook-readme/backwardCompatibility/with-readme.js' {
  declare module.exports: $Exports<'storybook-readme/backwardCompatibility/with-readme'>;
}
declare module 'storybook-readme/components/Marked/index.js' {
  declare module.exports: $Exports<'storybook-readme/components/Marked/index'>;
}
declare module 'storybook-readme/components/Preview/DocPreview.js' {
  declare module.exports: $Exports<'storybook-readme/components/Preview/DocPreview'>;
}
declare module 'storybook-readme/components/Preview/FooterPreview.js' {
  declare module.exports: $Exports<'storybook-readme/components/Preview/FooterPreview'>;
}
declare module 'storybook-readme/components/Preview/HeaderPreview.js' {
  declare module.exports: $Exports<'storybook-readme/components/Preview/HeaderPreview'>;
}
declare module 'storybook-readme/components/Preview/index.js' {
  declare module.exports: $Exports<'storybook-readme/components/Preview/index'>;
}
declare module 'storybook-readme/components/Preview/StoryPreview.js' {
  declare module.exports: $Exports<'storybook-readme/components/Preview/StoryPreview'>;
}
declare module 'storybook-readme/components/ReadmeContent/index.js' {
  declare module.exports: $Exports<'storybook-readme/components/ReadmeContent/index'>;
}
declare module 'storybook-readme/components/ReadmeSidebar/index.js' {
  declare module.exports: $Exports<'storybook-readme/components/ReadmeSidebar/index'>;
}
declare module 'storybook-readme/const.js' {
  declare module.exports: $Exports<'storybook-readme/const'>;
}
declare module 'storybook-readme/index' {
  declare module.exports: $Exports<'storybook-readme'>;
}
declare module 'storybook-readme/index.js' {
  declare module.exports: $Exports<'storybook-readme'>;
}
declare module 'storybook-readme/register.js' {
  declare module.exports: $Exports<'storybook-readme/register'>;
}
declare module 'storybook-readme/registerWithPanelTitle.js' {
  declare module.exports: $Exports<'storybook-readme/registerWithPanelTitle'>;
}
declare module 'storybook-readme/services/config.js' {
  declare module.exports: $Exports<'storybook-readme/services/config'>;
}
declare module 'storybook-readme/services/getDocsLayout.js' {
  declare module.exports: $Exports<'storybook-readme/services/getDocsLayout'>;
}
declare module 'storybook-readme/services/getParameters.js' {
  declare module.exports: $Exports<'storybook-readme/services/getParameters'>;
}
declare module 'storybook-readme/services/getPropsTables/index.js' {
  declare module.exports: $Exports<'storybook-readme/services/getPropsTables/index'>;
}
declare module 'storybook-readme/services/getPropsTables/parseProps.js' {
  declare module.exports: $Exports<'storybook-readme/services/getPropsTables/parseProps'>;
}
declare module 'storybook-readme/services/highlite.js' {
  declare module.exports: $Exports<'storybook-readme/services/highlite'>;
}
declare module 'storybook-readme/services/marked.js' {
  declare module.exports: $Exports<'storybook-readme/services/marked'>;
}
declare module 'storybook-readme/services/transformEmojis.js' {
  declare module.exports: $Exports<'storybook-readme/services/transformEmojis'>;
}
declare module 'storybook-readme/styles/codeThemeCss.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemeCss'>;
}
declare module 'storybook-readme/styles/codeThemes/a11y-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/a11y-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/a11y-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/a11y-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/agate.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/agate.css'>;
}
declare module 'storybook-readme/styles/codeThemes/an-old-hope.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/an-old-hope.css'>;
}
declare module 'storybook-readme/styles/codeThemes/androidstudio.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/androidstudio.css'>;
}
declare module 'storybook-readme/styles/codeThemes/arduino-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/arduino-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/arta.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/arta.css'>;
}
declare module 'storybook-readme/styles/codeThemes/ascetic.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/ascetic.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-cave-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-cave-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-cave-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-cave-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-dune-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-dune-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-dune-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-dune-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-estuary-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-estuary-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-estuary-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-estuary-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-forest-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-forest-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-forest-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-forest-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-heath-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-heath-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-heath-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-heath-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-lakeside-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-lakeside-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-lakeside-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-lakeside-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-plateau-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-plateau-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-plateau-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-plateau-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-savanna-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-savanna-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-savanna-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-savanna-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-seaside-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-seaside-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-seaside-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-seaside-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-sulphurpool-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-sulphurpool-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atelier-sulphurpool-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atelier-sulphurpool-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atom-one-dark-reasonable.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atom-one-dark-reasonable.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atom-one-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atom-one-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/atom-one-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/atom-one-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/codepen-embed.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/codepen-embed.css'>;
}
declare module 'storybook-readme/styles/codeThemes/color-brewer.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/color-brewer.css'>;
}
declare module 'storybook-readme/styles/codeThemes/darcula.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/darcula.css'>;
}
declare module 'storybook-readme/styles/codeThemes/dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/darkula.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/darkula.css'>;
}
declare module 'storybook-readme/styles/codeThemes/default.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/default.css'>;
}
declare module 'storybook-readme/styles/codeThemes/docco.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/docco.css'>;
}
declare module 'storybook-readme/styles/codeThemes/dracula.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/dracula.css'>;
}
declare module 'storybook-readme/styles/codeThemes/far.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/far.css'>;
}
declare module 'storybook-readme/styles/codeThemes/foundation.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/foundation.css'>;
}
declare module 'storybook-readme/styles/codeThemes/github-gist.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/github-gist.css'>;
}
declare module 'storybook-readme/styles/codeThemes/github.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/github.css'>;
}
declare module 'storybook-readme/styles/codeThemes/gml.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/gml.css'>;
}
declare module 'storybook-readme/styles/codeThemes/googlecode.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/googlecode.css'>;
}
declare module 'storybook-readme/styles/codeThemes/grayscale.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/grayscale.css'>;
}
declare module 'storybook-readme/styles/codeThemes/gruvbox-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/gruvbox-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/gruvbox-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/gruvbox-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/hopscotch.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/hopscotch.css'>;
}
declare module 'storybook-readme/styles/codeThemes/hybrid.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/hybrid.css'>;
}
declare module 'storybook-readme/styles/codeThemes/idea.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/idea.css'>;
}
declare module 'storybook-readme/styles/codeThemes/ir-black.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/ir-black.css'>;
}
declare module 'storybook-readme/styles/codeThemes/isbl-editor-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/isbl-editor-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/isbl-editor-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/isbl-editor-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/kimbie.dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/kimbie.dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/kimbie.light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/kimbie.light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/lightfair.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/lightfair.css'>;
}
declare module 'storybook-readme/styles/codeThemes/magula.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/magula.css'>;
}
declare module 'storybook-readme/styles/codeThemes/mono-blue.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/mono-blue.css'>;
}
declare module 'storybook-readme/styles/codeThemes/monokai-sublime.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/monokai-sublime.css'>;
}
declare module 'storybook-readme/styles/codeThemes/monokai.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/monokai.css'>;
}
declare module 'storybook-readme/styles/codeThemes/nord.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/nord.css'>;
}
declare module 'storybook-readme/styles/codeThemes/obsidian.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/obsidian.css'>;
}
declare module 'storybook-readme/styles/codeThemes/ocean.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/ocean.css'>;
}
declare module 'storybook-readme/styles/codeThemes/paraiso-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/paraiso-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/paraiso-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/paraiso-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/purebasic.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/purebasic.css'>;
}
declare module 'storybook-readme/styles/codeThemes/qtcreator_dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/qtcreator_dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/qtcreator_light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/qtcreator_light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/railscasts.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/railscasts.css'>;
}
declare module 'storybook-readme/styles/codeThemes/rainbow.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/rainbow.css'>;
}
declare module 'storybook-readme/styles/codeThemes/routeros.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/routeros.css'>;
}
declare module 'storybook-readme/styles/codeThemes/shades-of-purple.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/shades-of-purple.css'>;
}
declare module 'storybook-readme/styles/codeThemes/solarized-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/solarized-dark.css'>;
}
declare module 'storybook-readme/styles/codeThemes/solarized-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/solarized-light.css'>;
}
declare module 'storybook-readme/styles/codeThemes/sunburst.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/sunburst.css'>;
}
declare module 'storybook-readme/styles/codeThemes/tomorrow-night-blue.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/tomorrow-night-blue.css'>;
}
declare module 'storybook-readme/styles/codeThemes/tomorrow-night-bright.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/tomorrow-night-bright.css'>;
}
declare module 'storybook-readme/styles/codeThemes/tomorrow-night-eighties.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/tomorrow-night-eighties.css'>;
}
declare module 'storybook-readme/styles/codeThemes/tomorrow-night.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/tomorrow-night.css'>;
}
declare module 'storybook-readme/styles/codeThemes/tomorrow.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/tomorrow.css'>;
}
declare module 'storybook-readme/styles/codeThemes/vs.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/vs.css'>;
}
declare module 'storybook-readme/styles/codeThemes/vs2015.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/vs2015.css'>;
}
declare module 'storybook-readme/styles/codeThemes/xcode.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/xcode.css'>;
}
declare module 'storybook-readme/styles/codeThemes/xt256.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/xt256.css'>;
}
declare module 'storybook-readme/styles/codeThemes/zenburn.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/codeThemes/zenburn.css'>;
}
declare module 'storybook-readme/styles/githubMarkdownCss.js' {
  declare module.exports: $Exports<'storybook-readme/styles/githubMarkdownCss'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/a11y-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/a11y-dark.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/atom-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/atom-dark.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/base16-ateliersulphurpool.light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/base16-ateliersulphurpool.light.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/cb.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/cb.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/darcula.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/darcula.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/duotone-dark.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/duotone-dark.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/duotone-earth.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/duotone-earth.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/duotone-forest.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/duotone-forest.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/duotone-light.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/duotone-light.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/duotone-sea.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/duotone-sea.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/duotone-space.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/duotone-space.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/ghcolors.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/ghcolors.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/github.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/github.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/hopscotch.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/hopscotch.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/pojoaque.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/pojoaque.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/vs.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/vs.css'>;
}
declare module 'storybook-readme/styles/prismCodeThemes/xonokai.css.js' {
  declare module.exports: $Exports<'storybook-readme/styles/prismCodeThemes/xonokai.css'>;
}
declare module 'storybook-readme/styles/styleFactory.js' {
  declare module.exports: $Exports<'storybook-readme/styles/styleFactory'>;
}
declare module 'storybook-readme/vue/components/Preview/DocPreview.js' {
  declare module.exports: $Exports<'storybook-readme/vue/components/Preview/DocPreview'>;
}
declare module 'storybook-readme/vue/components/Preview/FooterPreview.js' {
  declare module.exports: $Exports<'storybook-readme/vue/components/Preview/FooterPreview'>;
}
declare module 'storybook-readme/vue/components/Preview/HeaderPreview.js' {
  declare module.exports: $Exports<'storybook-readme/vue/components/Preview/HeaderPreview'>;
}
declare module 'storybook-readme/vue/components/Preview/index.js' {
  declare module.exports: $Exports<'storybook-readme/vue/components/Preview/index'>;
}
declare module 'storybook-readme/vue/components/Preview/StoryPreview.js' {
  declare module.exports: $Exports<'storybook-readme/vue/components/Preview/StoryPreview'>;
}
declare module 'storybook-readme/vue/components/ReadmeContent/index.js' {
  declare module.exports: $Exports<'storybook-readme/vue/components/ReadmeContent/index'>;
}
declare module 'storybook-readme/vue/docs-loader.js' {
  declare module.exports: $Exports<'storybook-readme/vue/docs-loader'>;
}
declare module 'storybook-readme/vue/index.js' {
  declare module.exports: $Exports<'storybook-readme/vue/index'>;
}
declare module 'storybook-readme/vue/updateWebpackConfig.js' {
  declare module.exports: $Exports<'storybook-readme/vue/updateWebpackConfig'>;
}
declare module 'storybook-readme/with-docs.js' {
  declare module.exports: $Exports<'storybook-readme/with-docs'>;
}
declare module 'storybook-readme/with-readme.js' {
  declare module.exports: $Exports<'storybook-readme/with-readme'>;
}
