// flow-typed signature: b80819ce9f4cd75d7ebafa8d50ebe727
// flow-typed version: <<STUB>>/@babel/plugin-transform-template-literals_v^7.4.4/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-template-literals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-template-literals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-template-literals/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-template-literals/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-template-literals/lib/index'>;
}
