// flow-typed signature: bae14c99158f53a7145c1cc0d3c8d9cc
// flow-typed version: <<STUB>>/@babel/plugin-transform-block-scoping_v^7.4.4/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-block-scoping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-block-scoping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-block-scoping/lib/index' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-block-scoping/lib/tdz' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-block-scoping/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-block-scoping/lib/index'>;
}
declare module '@babel/plugin-transform-block-scoping/lib/tdz.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-block-scoping/lib/tdz'>;
}
