// flow-typed signature: 1b5f0a38ed92d675193a0c4caa9d4eb7
// flow-typed version: <<STUB>>/@storybook/cli_v^5.1.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/cli/bin/generate' {
  declare module.exports: any;
}

declare module '@storybook/cli/bin/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/ANGULAR/angular-helpers' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/ANGULAR/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/EMBER/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/EMBER/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/HTML/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/HTML/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/MARKO/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/MARKO/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/METEOR/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/METEOR/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/MITHRIL/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/MITHRIL/template/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/MITHRIL/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/MITHRIL/template/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/POLYMER/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/POLYMER/template/src/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/PREACT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/PREACT/template/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/PREACT/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/PREACT/template/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/rn-addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/RIOT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/RIOT/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/SFC_VUE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/SFC_VUE/template/src/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/SVELTE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/SVELTE/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/template/stories/MyButton' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/VUE/template/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/add' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/add.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/detect' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/detect.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/has_yarn' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/helpers' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/initiate' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/latest_version' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/npm_init' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/project_types' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/project_types.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/angular-cli-v6/src/karma.conf' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/angular-cli-v7/src/karma.conf' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/ember-cli/config/environment' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/ember-cli/config/targets' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/ember-cli/ember-cli-build' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/ember-cli/testem' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/ember-cli/tests/test-helper' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/meteor/client/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/meteor/server/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babel_6/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babel_6/rollup.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babel_config_js/babel.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babel_config_js/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babel_custom_preset/babel-preset-custom/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babel_custom_preset/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babel_pkg_json/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babelrc_js/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_babelrc/stories/index.stories' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native_scripts/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native_scripts/babel.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_native/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_project/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/serviceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/serviceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_scripts/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_static_next/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_static_next/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_static_next/static.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_static/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_static/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react_static/static.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/react/rollup.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/riot/public/assets/js/app' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/riot/src/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/riot/webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/config/dev.env' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/config/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/config/prod.env' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/sfc_vue/src/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App.test' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/vue/public/assets/js/app' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/vue/rollup.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/vue/src/main' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/webpack_react_frozen_lock/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/webpack_react_frozen_lock/webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/webpack_react/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/test/fixtures/webpack_react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/cli/bin/generate.js' {
  declare module.exports: $Exports<'@storybook/cli/bin/generate'>;
}
declare module '@storybook/cli/bin/index.js' {
  declare module.exports: $Exports<'@storybook/cli/bin/index'>;
}
declare module '@storybook/cli/generators/ANGULAR/angular-helpers.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/ANGULAR/angular-helpers'>;
}
declare module '@storybook/cli/generators/ANGULAR/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/ANGULAR/index'>;
}
declare module '@storybook/cli/generators/EMBER/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/EMBER/index'>;
}
declare module '@storybook/cli/generators/EMBER/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/EMBER/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/HTML/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/HTML/index'>;
}
declare module '@storybook/cli/generators/HTML/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/HTML/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/MARKO/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/MARKO/index'>;
}
declare module '@storybook/cli/generators/MARKO/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/MARKO/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/METEOR/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/METEOR/index'>;
}
declare module '@storybook/cli/generators/METEOR/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/METEOR/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/MITHRIL/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/MITHRIL/index'>;
}
declare module '@storybook/cli/generators/MITHRIL/template/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/MITHRIL/template/stories/Button'>;
}
declare module '@storybook/cli/generators/MITHRIL/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/MITHRIL/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/MITHRIL/template/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/MITHRIL/template/stories/Welcome'>;
}
declare module '@storybook/cli/generators/POLYMER/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/POLYMER/index'>;
}
declare module '@storybook/cli/generators/POLYMER/template/src/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/POLYMER/template/src/stories/index.stories'>;
}
declare module '@storybook/cli/generators/PREACT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/PREACT/index'>;
}
declare module '@storybook/cli/generators/PREACT/template/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/PREACT/template/stories/Button'>;
}
declare module '@storybook/cli/generators/PREACT/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/PREACT/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/PREACT/template/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/PREACT/template/stories/Welcome'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/addons.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/addons'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/rn-addons.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/rn-addons'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/index'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index'>;
}
declare module '@storybook/cli/generators/REACT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/index'>;
}
declare module '@storybook/cli/generators/REACT/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/RIOT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/RIOT/index'>;
}
declare module '@storybook/cli/generators/RIOT/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/RIOT/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/SFC_VUE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/SFC_VUE/index'>;
}
declare module '@storybook/cli/generators/SFC_VUE/template/src/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/SFC_VUE/template/src/stories/index.stories'>;
}
declare module '@storybook/cli/generators/SVELTE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/SVELTE/index'>;
}
declare module '@storybook/cli/generators/SVELTE/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/SVELTE/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index'>;
}
declare module '@storybook/cli/generators/VUE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/index'>;
}
declare module '@storybook/cli/generators/VUE/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/template/stories/index.stories'>;
}
declare module '@storybook/cli/generators/VUE/template/stories/MyButton.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/template/stories/MyButton'>;
}
declare module '@storybook/cli/generators/VUE/template/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/VUE/template/stories/Welcome'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/index'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/template/stories/index.stories'>;
}
declare module '@storybook/cli/lib/add.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/add'>;
}
declare module '@storybook/cli/lib/add.test.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/add.test'>;
}
declare module '@storybook/cli/lib/detect.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/detect'>;
}
declare module '@storybook/cli/lib/detect.test.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/detect.test'>;
}
declare module '@storybook/cli/lib/has_yarn.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/has_yarn'>;
}
declare module '@storybook/cli/lib/helpers.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/helpers'>;
}
declare module '@storybook/cli/lib/initiate.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/initiate'>;
}
declare module '@storybook/cli/lib/latest_version.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/latest_version'>;
}
declare module '@storybook/cli/lib/npm_init.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/npm_init'>;
}
declare module '@storybook/cli/lib/project_types.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/project_types'>;
}
declare module '@storybook/cli/lib/project_types.test.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/project_types.test'>;
}
declare module '@storybook/cli/test/fixtures/angular-cli-v6/src/karma.conf.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/angular-cli-v6/src/karma.conf'>;
}
declare module '@storybook/cli/test/fixtures/angular-cli-v7/src/karma.conf.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/angular-cli-v7/src/karma.conf'>;
}
declare module '@storybook/cli/test/fixtures/ember-cli/config/environment.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/ember-cli/config/environment'>;
}
declare module '@storybook/cli/test/fixtures/ember-cli/config/targets.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/ember-cli/config/targets'>;
}
declare module '@storybook/cli/test/fixtures/ember-cli/ember-cli-build.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/ember-cli/ember-cli-build'>;
}
declare module '@storybook/cli/test/fixtures/ember-cli/testem.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/ember-cli/testem'>;
}
declare module '@storybook/cli/test/fixtures/ember-cli/tests/test-helper.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/ember-cli/tests/test-helper'>;
}
declare module '@storybook/cli/test/fixtures/meteor/client/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/meteor/client/main'>;
}
declare module '@storybook/cli/test/fixtures/meteor/server/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/meteor/server/main'>;
}
declare module '@storybook/cli/test/fixtures/react_babel_6/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babel_6/index'>;
}
declare module '@storybook/cli/test/fixtures/react_babel_6/rollup.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babel_6/rollup.config'>;
}
declare module '@storybook/cli/test/fixtures/react_babel_config_js/babel.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babel_config_js/babel.config'>;
}
declare module '@storybook/cli/test/fixtures/react_babel_config_js/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babel_config_js/stories/index.stories'>;
}
declare module '@storybook/cli/test/fixtures/react_babel_custom_preset/babel-preset-custom/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babel_custom_preset/babel-preset-custom/index'>;
}
declare module '@storybook/cli/test/fixtures/react_babel_custom_preset/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babel_custom_preset/stories/index.stories'>;
}
declare module '@storybook/cli/test/fixtures/react_babel_pkg_json/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babel_pkg_json/stories/index.stories'>;
}
declare module '@storybook/cli/test/fixtures/react_babelrc_js/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babelrc_js/stories/index.stories'>;
}
declare module '@storybook/cli/test/fixtures/react_babelrc/stories/index.stories.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_babelrc/stories/index.stories'>;
}
declare module '@storybook/cli/test/fixtures/react_native_scripts/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native_scripts/App'>;
}
declare module '@storybook/cli/test/fixtures/react_native_scripts/babel.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native_scripts/babel.config'>;
}
declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/__tests__/index.android'>;
}
declare module '@storybook/cli/test/fixtures/react_native/__tests__/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/__tests__/index.ios'>;
}
declare module '@storybook/cli/test/fixtures/react_native/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/index.android'>;
}
declare module '@storybook/cli/test/fixtures/react_native/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_native/index.ios'>;
}
declare module '@storybook/cli/test/fixtures/react_project/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_project/index'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2_forked/src/App'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2_forked/src/App.test'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2_forked/src/index'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2_forked/src/serviceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2_forked/src/serviceWorker'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2/src/App'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2/src/App.test'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2/src/index'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts_v2/src/serviceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts_v2/src/serviceWorker'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/App'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/App.test'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/index'>;
}
declare module '@storybook/cli/test/fixtures/react_scripts/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_scripts/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/fixtures/react_static_next/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_static_next/src/App'>;
}
declare module '@storybook/cli/test/fixtures/react_static_next/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_static_next/src/index'>;
}
declare module '@storybook/cli/test/fixtures/react_static_next/static.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_static_next/static.config'>;
}
declare module '@storybook/cli/test/fixtures/react_static/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_static/src/App'>;
}
declare module '@storybook/cli/test/fixtures/react_static/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_static/src/index'>;
}
declare module '@storybook/cli/test/fixtures/react_static/static.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react_static/static.config'>;
}
declare module '@storybook/cli/test/fixtures/react/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react/index'>;
}
declare module '@storybook/cli/test/fixtures/react/rollup.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/react/rollup.config'>;
}
declare module '@storybook/cli/test/fixtures/riot/public/assets/js/app.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/riot/public/assets/js/app'>;
}
declare module '@storybook/cli/test/fixtures/riot/src/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/riot/src/main'>;
}
declare module '@storybook/cli/test/fixtures/riot/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/riot/webpack.config'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/config/dev.env.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/config/dev.env'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/config/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/config/index'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/config/prod.env.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/config/prod.env'>;
}
declare module '@storybook/cli/test/fixtures/sfc_vue/src/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/sfc_vue/src/main'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/App'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/App.test.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/App.test'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/index'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/src/registerServiceWorker'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/stories/Button'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/stories/index'>;
}
declare module '@storybook/cli/test/fixtures/update_package_organisations/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/update_package_organisations/stories/Welcome'>;
}
declare module '@storybook/cli/test/fixtures/vue/public/assets/js/app.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/vue/public/assets/js/app'>;
}
declare module '@storybook/cli/test/fixtures/vue/rollup.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/vue/rollup.config'>;
}
declare module '@storybook/cli/test/fixtures/vue/src/main.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/vue/src/main'>;
}
declare module '@storybook/cli/test/fixtures/webpack_react_frozen_lock/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/webpack_react_frozen_lock/index'>;
}
declare module '@storybook/cli/test/fixtures/webpack_react_frozen_lock/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/webpack_react_frozen_lock/webpack.config'>;
}
declare module '@storybook/cli/test/fixtures/webpack_react/index.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/webpack_react/index'>;
}
declare module '@storybook/cli/test/fixtures/webpack_react/webpack.config.js' {
  declare module.exports: $Exports<'@storybook/cli/test/fixtures/webpack_react/webpack.config'>;
}
